# Generated by Django 4.2.4 on 2023-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_facilityfeedback_cleanliness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedback',
            name='effectiveness',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Very Good'), (3, 'Good'), (2, 'Fair'), (1, 'Poor')]),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='interest',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Very Good'), (3, 'Good'), (2, 'Fair'), (1, 'Poor')]),
        ),
    ]
